//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.PatnerProduct = new HashSet<PatnerProduct>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Article { get; set; }
        public double MinCoastForPartner { get; set; }
        public int ProductTypeID { get; set; }
        public int MaterialTypeID { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatnerProduct> PatnerProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
